### PR TITLE
Remove evercrypt

### LINKED ISSUE #1399: [Bug]
**Describe the bug**
Trying to build openmls with cargo build on ubuntu 22.04 leads to an error in evercrypt-sys build:

 ============== build log ==================
error: failed to run custom build command for `evercrypt-sys v0.0.9`

Caused by:
  process didn't exit successfully: `/openmls/target/debug/build/evercrypt-sys-a404c0ddf12a0050/build-script-build` (exit status: 101)
stdout
  cargo:rerun-if-changed=wrapper.h
  cargo:rerun-if-changed=hacl-star
  build_config: BuildConfig { hacl_src_dir: "gcc-compatible", cross: false, config_flags: [], make_flags: [], env: {}, lib_name: "evercrypt", windows: false }
  out_path: "/openmls/target/debug/build/evercrypt-sys-b16f6fec2c5ef37b/out"
  hacl_src_path: "/openmls/target/debug/build/evercrypt-sys-b16f6fec2c5ef37b/out/hacl-star/dist/gcc-compatible"

stderr
  /openmls/target/debug/build/evercrypt-sys-b16f6fec2c5ef37b/out/hacl-star/dist/gcc-compatible/evercrypt_targetconfig.h:36:10: fatal error: 'stdbool.h' file not found
  /openmls/target/debug/build/evercrypt-sys-b16f6fec2c5ef37b/out/hacl-star/dist/gcc-compatible/evercrypt_targetconfig.h:36:10: fatal error: 'stdbool.h' file not found, err: true

 ==================================

The build search for C headers, but the headers are not located within /usr/include.
The headers are present in other folders:
/usr/lib/gcc/x86_64-linux-gnu/9/include/stdbool.h
/usr/lib/gcc/x86_64-linux-gnu/11/include/stdbool.h
/usr/lib/gcc/x86_64-linux-gnu/10/include/stdbool.h
/usr/include/c++/11/tr1/stdbool.h

**To Reproduce**
On ubuntu :
1. git clone git@github.com:openmls/openmls.git
2. sudo apt-get install libssl-dev
3. sudo apt-get install protobuf-compiler
4. cd openmls
5. cargo build

After a while, you should have the error.

**Expected behavior**
cargo build should build the workspace and the evercrypt-sys build should find the headers in the appropriate location, or should provide a mean to give additional include paths.

**Platform (please complete the following information):**
 - Linux Ubuntu 22.04 LTS
 - x86_64

### PR DESCRIPTION
**Pull request by kkohbrok**
Fixes #1399.

### CODE REVIEW

File: Developer.md [hunk 1]
```diff
@@ -10,10 +10,9 @@ the current state of the `main` branch as well.
 This repository is a cargo workspace with the OpenMLS library as the main component.
 
 In order to use OpenMLS an implementation of the [traits](https://github.com/openmls/openmls/tree/main/traits) is required.
-This repository provides two default implementations
+This repository provides one default implementations
```
Comment (raphaelrobert) [inline Developer.md:13]:
```suggestion
This repository provides default implementations
```

File: book/src/traits/traits.md [hunk 2]
```diff
@@ -6,20 +6,14 @@
 
 Because implementing the `OpenMLSCryptoProvider` is challenging, requires
 tremendous care, and is not what the average OpenMLS consumer wants to (or should) do,
-we provide two implementations that can be used.
+we provide one implementations that can be used.
```
Comment (raphaelrobert) [inline book/src/traits/traits.md:9]:
```suggestion
we provide a implementation that can be used.
```

**Review by raphaelrobert — CHANGES_REQUESTED** [review]
Thanks, just some nits
